framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
<<<<<<< HEAD
            sync: 'sync://'
=======
<<<<<<< HEAD
            # sync: 'sync://'
=======
            sync: 'sync://'
>>>>>>> isramedi
>>>>>>> 4f714e473f4c6306d8cd13fadaae1828cd26d7f1

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
<<<<<<< HEAD
            # En dev : envoi immédiat (pas besoin de lancer messenger:consume)
            # En prod : utiliser async et lancer un worker
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
=======
<<<<<<< HEAD
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
=======
            # En dev : envoi immédiat (pas besoin de lancer messenger:consume)
            # En prod : utiliser async et lancer un worker
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
>>>>>>> isramedi
>>>>>>> 4f714e473f4c6306d8cd13fadaae1828cd26d7f1
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
