twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
<<<<<<< HEAD
=======
<<<<<<< HEAD

=======
>>>>>>> isramedi
>>>>>>> 4f714e473f4c6306d8cd13fadaae1828cd26d7f1
when@test:
    twig:
        strict_variables: true
